#!/bin/bash

echo "iniciando memoria"

export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:~/workspace/Segmentation-Fault/tp-2019-1c-Segmentation-Fault/BibliotecaCompartida/Debug

gcc -I"/home/utnso/workspace/Segmentation-Fault/tp-2019-1c-Segmentation-Fault/BibliotecaCompartida" -O0 -g3 -Wall -c -fmessage-length=0 -MMD -MP -MT"PoolMemorias.o" -o "PoolMemorias.o" "PoolMemorias.c"

gcc -L"/home/utnso/workspace/Segmentation-Fault/tp-2019-1c-Segmentation-Fault/BibliotecaCompartida/Debug" -o "PoolMemorias"  PoolMemorias.o   -lBibliotecaCompartida -lrt -lm -lreadline -lpthread -lcommons
